
version: 2.1

orbs:
   heroku: circleci/heroku@1.2.6

jobs:
  build-test-analyze:
     working_directory: ~/Frontend
     docker:
          - image: circleci/node:12.18.2
     steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run: 
          name: Build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
workflows:
  deploy-workflow:
    jobs:
      - build-test-analyze
      - heroku/deploy-via-git:
          name: deploy-frontend
          app-name: rocky-ravine-63735
          filters:
            branches:
              only:
                - master
          requires:
            - build-test-analyze
 